# Generated by Django 3.0.5 on 2020-04-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataCubeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('vintage', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('wineProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataCubeApp.WineProducer')),
            ],
        ),
    ]
